### PR TITLE
fix: minor ui improvements

### LINKED ISSUE #26: Success Animation
Replace the current success animation with a colored version.

### LINKED ISSUE #28: Disable buttons while active
Disable buttons while loading (e.g. prevent paying the same invoice twice by double-tapping pay button).

### LINKED ISSUE #40: New wallet notification covers paste button
image

I think there might be other instances around the app too with a similar problem. Not sure what the best solution is. @reneaaron do you have any ideas?

### PR DESCRIPTION
**Pull request by reneaaron**
- Fixes #28
 - Button radius for smaller primary buttons
 - Fixes #26 
 - Fixes #40
 - Refactored Send / ConnectWallet screens to use a common QRCodeScanner component
 - App Icon in black / white
 - Corrected icon imports

### CODE REVIEW

File: pages/receive/ReceiveSuccess.tsx [hunk 1]
```diff
@@ -36,8 +36,8 @@ export function ReceiveSuccess() {
           </Text>
         </View>
         {getFiatAmount &&
-          <Text className="text-muted-foreground text-2xl font-bold">
-            {getFiatAmount(123) ?? ""}
+          <Text className="text-muted-foreground text-2xl font-semibold2">
```
Comment (im-adithya) [inline pages/receive/ReceiveSuccess.tsx:39]: typo: `font-semibold`

Comment (reneaaron) [reply pages/receive/ReceiveSuccess.tsx:39]: no, it's semibold2 and it's used across our codebase. for some reason I can't seem to manage to get the built-in tailwind classes to render other fonts :shrug:

Comment (im-adithya) [reply pages/receive/ReceiveSuccess.tsx:39]: Oh didn't notice, sorry!
